### ISSUE TITLE
Options for front page images 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#102]
Opening this issue for discussion about the images on the [front page](https://carp-new-website.netlify.app/).

- The top image - Do we have credit/permission to use that image? @OscarSiba has noted that we may not.
- The second image - Can we look for images that showcase more diversity?

**Comment by ErinBecker** [comment]
Based on a [reverse image search](https://tineye.com/search/88274c69ddd73f8c9254abac920bcc354ba49acf?sort=score&order=desc&page=1), the banner image seems to be a stock photo. 

We have access to a lot of stock photos in Canva, and could likely find another one that showcases more diversity (for the second image). I'm looking now and will add some options in thread.

**Comment by maneesha** [comment]
Assigning to @OscarSiba  as lead but anyone is welcome to offer feedback.

**Comment by elletjies** [comment]
Do we not have photos from our community we can use?

**Comment by sheraaronhurt** [comment]
Like the idea of using images from the community. Preferably a divers image since the words directly below says "Our diverse and global community is comprised of"

**Comment by OscarSiba** [comment]
The use of pictures from the community is tricky @sheraaronhurt @elletjies. We would need to make sure we have permission not just from the photographer, but from every person who is identifiable in the image; this will take time. Instead I will search for a more diverse image, but I had chosen this one because the header image is of black people, and this was meant to bring some balance. But ideally we should have more diverse crowd to represent the workshops.

**Comment by OscarSiba** [comment]
Please replace the second image on the front page with "pexels-fauxels-3184302.jpg" from this [images folder](https://drive.google.com/drive/folders/1Vz0H75cLMvx-pdmi57ZQDuip_fOb6S_A).

**Comment by maneesha** [comment]
@OscarSiba  Please review the images on the front page. Close this issue if it all looks good to you, or leave any other feedback here.
