### ISSUE TITLE
Style and error changes to the Community pages

### ISSUE THREAD

**Issue by OscarSiba** [carpentries/new-website#212]
---

**Our Community**: https://carp-new-website.netlify.app/community/

- [x] Under "Our Volunteer Communities: please put a full stop at the end of each listed community role. 
- [x] For the Code of Conduct Committee bullet point, please make "keep" to be "keeps". 
- [x] This page does not have the Lesson Developers community role listed. Compare to the [Get Involved](https://carp-new-website.netlify.app/community/get-involved/#lesson-developers) page. CC @elletjies for input. 

**Instructors**: https://carp-new-website.netlify.app/community/instructors/

- [x] In the first and second sentences, please change "Carpentry" to be "Carpentries".
- [x] The link in the following sentence leads to the old website: "Read more about our Instructors on [The Carpentries website](https://carpentries.org/community/#instructors)." Where is this supposed to link to on the new website? 
- [x] The link in the following sentence leads to the old website: [View a map of our Instructors](https://carpentries.org/instructors-map/)

**Our Instructor Trainers**: https://carp-new-website.netlify.app/community/instructor-trainers/

- [x] In the first sentence, please change "prepare" to "train". 
- [x] Please delete this sentence: "They showcase and embody the enthusiasm and conduct of our community as they prepare new Instructors."
- [x] Please rephase "Trainers scale their impact..." and "Trainers may temporarily or permanently..." to "Instructor "Trainers scale their impact..."and "Instructor Trainers may temporarily or permanently..."  

**Get Connected**:  https://carp-new-website.netlify.app/community/get-connected/

- [x] Please change "Subcommunities" title to "Subcommunity Registry".  
- [x] Under Carpentries Italia, please change "organized" to "organised".
- [x] The link to the [The Carpentries in Australia](https://carpentries.org/regions_au/) leads to the old website. Where in the new website is this supposed to go? CC @elletjies for input. 
- [x] Under the same subcommunity, after mention of New Zealand, please add a stroke / and "Aotearoa". I.e. "We often link our activities with the equivalent subcommunity in New Zealand/Aotearoa."
- [x] Under the PyAOS Carpentry entry the LinkedIn link is not working. CC @elletjies for input. 
- [x] The hyperlink to [Carpentries at Stanford University](https://library.stanford.edu/research/carpentries-stanford) leads to an empty page. Their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentry@lists.stanford.edu) also leads to a 404 error page. CC @elletjies for input. 
- [x] Please title the "New Zealand" subcommunity "New Zealand/Aotearoa". Also on the paragraph description please add a / between Aotearoa and New Zealand. 
- [x] Under UW-Madison Carpentries Community entry, please capitalise the initial letters in 'Lesson Developers". 
- [x] Note also that the link to their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentries@g-groups.wisc.edu) leads to a 404 error. CC @elletjies for input.
- [x] Under Smithsonian Institution Carpentries, please spell "organization" with an s instead of z. And spell it as Member Organisation. 
- [x] Under Carpentry @ UiO, please refer to "Instructor Trainers" instead of just "Trainers".
- [x] Under Carpentries @ VT, please change "Trainees" to "Instructors Trainees". 
- [x] Under Carpentries México, please capitalise "I" in Instructor.  
- [x] Please note also that their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentries-mexico@googlegroups.com) leads to a 404 error. CC @elletjies for input.

---

**Comment by elletjies** [comment]
- [X]  Under "Our Volunteer Communities: please put a full stop at the end of each listed community role.
- [X]  For the Code of Conduct Committee bullet point, please make "keep" to be "keeps".
- [X] - This page does not have the Lesson Developers community role listed. Compare to the [Get Involved](https://carp-new-website.netlify.app/community/get-involved/#lesson-developers) page. CC @elletjies for input.

https://github.com/carpentries/new-website/pull/214

**Comment by elletjies** [comment]
@maneesha I will make the changes for Get Involved.

**Comment by OscarSiba** [comment]
> @maneesha I will make the changes for Get Involved.

Before you do @elletjies, please first see the suggested changes in the [Get Involved](https://github.com/carpentries/new-website/issues/215) issue.

**Comment by elletjies** [comment]
- [X] Please change "Subcommunities" title to "Subcommunity Registry".
- [X]  Under Carpentries Italia, please change "organized" to "organised".
- [X]  The link to the [The Carpentries in Australia](https://carpentries.org/regions_au/) leads to the old website. Where in the new website is this supposed to go? CC @elletjies for input. **Removed the link**
- [X]  Under the same subcommunity, after mention of New Zealand, please add a stroke / and "Aotearoa". I.e. "We often link our activities with the equivalent subcommunity in New Zealand/Aotearoa."
- [x]  Under the PyAOS Carpentry entry the LinkedIn link is not working. CC @elletjies for input. **Removed the link**
- [X]  The hyperlink to [Carpentries at Stanford University](https://library.stanford.edu/research/carpentries-stanford) leads to an empty page. Their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentry@lists.stanford.edu) also leads to a 404 error page. CC @elletjies for input.
- [X]  Please title the "New Zealand" subcommunity "New Zealand/Aotearoa". Also on the paragraph description please add a / between Aotearoa and New Zealand.
- [X]  Under UW-Madison Carpentries Community entry, please capitalise the initial letters in 'Lesson Developers".
- [X]  Note also that the link to their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentries@g-groups.wisc.edu) leads to a 404 error. CC @elletjies for input.
- [X]  Under Smithsonian Institution Carpentries, please spell "organization" with an s instead of z. And spell it as Member Organisation.
- [X]  Under Carpentry @ UiO, please refer to "Instructor Trainers" instead of just "Trainers".
- [X]  Under Carpentries @ VT, please change "Trainees" to "Instructors Trainees". **They are referring to those they train**
- [X]  Under Carpentries México, please capitalise "I" in Instructor.
- [X]  Please note also that their [Mailing list](https://carp-new-website.netlify.app/community/get-connected/carpentries-mexico@googlegroups.com) leads to a 404 error. CC @elletjies for input. **Removed**

**Comment by elletjies** [comment]
> > @maneesha I will make the changes for Get Involved.
> 
> Before you do @elletjies, please first see the suggested changes in the [Get Involved](https://github.com/carpentries/new-website/issues/215) issue.

I already made the changes. Will take a look again later this week

**Comment by maneesha** [comment]
Making note that I checked off all the things that @elletjies put in new comments.

**Comment by maneesha** [comment]
Addressed with #214, #216, #218, #219
