### ISSUE TITLE
Update sponsors on front page 

### ISSUE THREAD

**Issue by maneesha** [carpentries/new-website#64]
@OscarSiba has recommended adding Posit to the list of supporters on our front page, but also wants to defer to Kari on this.  Leaving note here to come back to this.  
If we add Posit, we will also need to transform an svg logo to grayscale to match the theme.

(Oscar, you don't need to do anything until we consult with Kari)

**Comment by maneesha** [comment]
Tagging @ErinBecker  in case you have any suggestions in Kari's absence

**Comment by maneesha** [comment]
Temporarily assigning to @ErinBecker  - Erin, please leave a note here if you have recommendations on what to do now, or if you would like to wait for Kari.

**Comment by maneesha** [comment]
Once we confirm what organisations should be listed, I will make sure all the logos link to their sites.

**Comment by ErinBecker** [comment]
I agree that Posit should be shown in the list of supporters. Currently RStudio is shown. RStudio has been re-branded to Posit, so RStudio should be removed and replaced with Posit. 

<img width="1063" alt="Screenshot 2024-09-19 at 9 01 18 AM" src="https://github.com/user-attachments/assets/1b9cfc63-428f-4fc9-b8d9-0fb5e32a9143">

**Comment by maneesha** [comment]
@OscarSiba  Where can we get a Posit logo we can use on our site?

**Comment by maneesha** [comment]
Note also that our current supporters page is much longer.  Do we need something like this on our new site? https://carpentries.org/supporters/

**Comment by OscarSiba** [comment]
I think we can use the same Posit logo as is currently on our website here: https://carpentries.org/sponsorship/

**Comment by maneesha** [comment]
@OscarSiba  The posit logo has been added for your review.  

Please also see my question above about the current sponsors page.

**Comment by ErinBecker** [comment]
Thanks for raising the question about the current sponsors page @maneesha. This page [hasn't been updated since 2022](https://github.com/carpentries/carpentries.org/commits/main/pages/supporters.md), and[ isn't linked to from any of our other pages](https://github.com/search?q=repo%3Acarpentries%2Fcarpentries.org%20supporters.md&type=code), with the exception of the blog post in which it was launched. Given that, and the overall goal of making our website more streamlined, less text-heavy, and easier to navigate, I approve not adding a long-format supporters page to the new website.

**Comment by maneesha** [comment]
We will not have a sponsors page on the new site.

@OscarSiba can you please confirm that the section sponsors logos as displayed on the front page is correct? If so, you can close this issue. Otherwise, please share any other feedback.
